apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  NODE_ENV: "production"
  REDIS_HOST: "redis-service" # This will be the name of our K8s Redis service
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  # K8s will base64 encode these automatically when using stringData
  DATABASE_URL: "postgresql://postgres:postgres@postgres-service:5432/snapbulance?schema=public"
  JWT_SECRET: "your_ultra_secure_production_key"